swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile
      description: API for fetching data of user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Data of User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: successful request
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
          
          
  /user/accounts/{account_id}:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: User Account API
      description: API for fetching a user Account
      produces:
        - application/json
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - name: account_id
          in: path
          description: account data recovery
          required: true
          type: string
      responses:
        '200':
          description: successful request
          schema:
            $ref: '#/definitions/LastTransactions'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
          
  /user/accounts/{account_id}/transactions/{transaction_id}:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: transaction's details of User account
      description: API for fetching details of a transaction
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - name: account_id
          in: path
          description: account data recovery
          required: true
          type: string
        - name: transaction_id
          in: path
          description: transaction id
          required: true
          type: string
      responses:
        '200':
          description: successful request
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
          
    post:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: post new information of transaction
      description: add a transaction information
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: "string"
          required: true
        - in: path
          type: number
          name: account_id
          description: account id
          required: true
        - in: path
          type: number
          name: transaction_id
          description: transaction id
          required: true
        - in: body
          name: body
          description: Post new information of transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionWithNewInfo'
      produces:
        - application/json
      responses:
        '200':
          description: Additional transaction informations created successully
          schema:
            $ref: '#/definitions/PostInfosTransactionResponse'  
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
    put:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Update transaction
      description: Update user Transaction
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - name: account_id
          in: path
          description: account id
          required: true
          type: string
        - name: transaction_id
          in: path
          description: transaction id
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction data
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      responses:
        '200':
          description: Transaction update successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
          
    delete:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Delete information  transaction
      description: deleteinformation transaction selected with id
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: account_id
          type: string
          required: true
          description:  account id
        - in: path
          name: transaction_id
          type: string
          required: true
          description:  transaction id
        - in: body
          name: body
          description: transaction selected
          required: true
          schema:
            $ref: '#/definitions/DeleteTransaction'
      produces:
        - application/json
      responses:
        '200':
          description: transaction deleted successully
          schema:
            $ref: '#/definitions/DeleteTransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  
          
          
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  LastTransactions:
    type: object
    properties:
      Account_id:
        type: string
      body:
        $ref: '#/definitions/TransactionsDetails'
        
  TransactionsDetails:
    type: object
    properties:
      transactions:
        type: array
        items:
          type: object
          properties:
            transaction_id:
              type: string
            date:
              type: string
            description:
              type: string
            amount:
              type: number
            balance:
              type: number
            transaction_type:
              type: string
            category:
              type: string
            notes:
              type: string
              
  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
        example: 200
      message:
        type: string
        example: successfully
      body:
        $ref: '#/definitions/Transaction'
        
  DeleteTransactionResponse:
    type: object
    properties:
      status:
        type: integer
        example: 200
      message:
        type: string
        example: transaction deleted successfully
        
  Transaction:
    type: object
    properties:
      transaction_id:
        type: string
        description: transaction's ID
      date:
        type: string
        description: transaction's date
      description:
        type: string
        description: transaction's description
      amount:
        type: integer
        format: number
        description: transaction's amount
      balance:
        type: integer
        format: number
        description: account balance after transaction
      transaction_type:
        type: string
        description: transaction's type
      category:
        type: string
        description: transaction's category
      notes:
        type: string
        description: transaction's notes
        
  TransactionWithNewInfo:
    type: object
    properties:
      transaction_id:
        type: string
        description: transaction's ID
      date:
        type: string
        description: transaction's date
      description:
        type: string
        description: transaction's description
      amount:
        type: integer
        format: number
        description: transaction's amount
      balance:
        type: integer
        format: number
        description: account balance after transaction
      transaction_type:
        type: string
        description: transaction's type
      category:
        properties:
          travel:
            type: string
            description: travel information
      notes:
        type: string
        description: transaction's notes
        
  PostInfosTransactionResponse:
    type: object
    properties:
      status:
        type: integer
        example: 200
      message:
        type: string
        example: successfully
      body:
        $ref: '#/definitions/TransactionWithNewInfo'
        
  DeleteTransaction:
    properties:
       transaction_id:
          type: string
          description: user email
        
  TransactionExample:
    type: object
    properties:
      transaction_id:
        type: string
        description: transaction's ID
        example: ku4yf684fyj87
      date:
        type: string
        format: date-time
        description: transaction's date
        example: '2022-08-02'
      description:
        type: string
        description: transaction's description
        example: Family trip to usa
      amount:
        type: integer
        format: number
        description: transaction's amount
        example: 4380
      balance:
        type: integer
        format: number
        description: account balance after transaction
        example: 1000
      transaction_type:
        type: string
        description: transaction's type
        example: Trip to usa
      category:
        type: string
        description: transaction's category
        example: guided tour
      notes:
        type: string
        description: transaction's notes
        example: travel company